/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TitleEnglish = string;
export type TitleGerman = string;
export type DescriptionEnglish = string;
export type DescriptionGerman = string;
export type Category = "Backend" | "Frontend" | "Tools" | "Management" | "Language";
export type Importance = number;
export type URL = string;
export type Logo = string;
export type LogoSourceAndOrCopyright = string;
export type FromDate = string;
export type ToDate = string;
export type Comment = string;
export type IsPersonalExperience = boolean;
export type IsBusinessExperience = boolean;
export type IsTrainingExperience = boolean;
export type Frequency = "infrequently" | "occasionally" | "regularly";
export type Experiences = Experience[];
export type SelfEvaluation = "Professional" | "Intermediate" | "Beginner";
export type Portfolio = Skill[];

export interface Skill {
  titleEnglish: TitleEnglish;
  titleGerman: TitleGerman;
  descriptionEnglish: DescriptionEnglish;
  descriptionGerman: DescriptionGerman;
  category: Category;
  importance: Importance;
  url?: URL;
  logo?: Logo;
  "logo-copyright"?: LogoSourceAndOrCopyright;
  experiences: Experiences;
  selfEvaluation: SelfEvaluation;
  [k: string]: unknown;
}
export interface Experience {
  from: FromDate;
  to?: ToDate;
  comment?: Comment;
  personal?: IsPersonalExperience;
  business?: IsBusinessExperience;
  training?: IsTrainingExperience;
  frequency: Frequency;
  [k: string]: unknown;
}
